baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'

[[menus.main]]
name = 'Lorem'
pageRef = '/ex'

[[menus.main]]
name = 'Ipsum'
pageRef = '/exa'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
