baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Accueil'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Categories'
pageRef = '/categories'
weight = 20

[[menus.main]]
name = 'Contribuer'
pageRef = '/contribuer'
weight = 40

[[menus.main]]
name = 'A propos'
pageRef = '/apropos'
weight = 50

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
