baseURL = 'https://sans-treve.org/'
languageCode = 'fr-fr'
title = 'Sans-trêve'
theme = 'basic'

# Twitter cards
[Params]
	twittercard_site = "@sans-treve"
	twittercard_creator = "@sans-treve"
	twittercard_previewimage = "/sans-treve-media/logo/logo1.jpeg"
	twitter_description = "Média d'intervention pour la révolution !"

[pagination]
	pagerSize = 9